# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20170917_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_choices', to='question.Question'),
        ),
    ]
