# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20170917_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionChoice',
            new_name='QuestionAlternative',
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_choice', to='question.QuestionAlternative'),
        ),
    ]
