# Generated by Django 2.0.2 on 2018-02-24 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20171119_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.Question')),
            ],
        ),
        migrations.AddField(
            model_name='questionalternative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionalternative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
